apiVersion: v1
kind: PersistentVolume
metadata:
  name: venv-cache-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-venv
  hostPath:
    path: /tmp/venvs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: venv-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-venv
  resources:
    requests:
      storage: 5Gi
